name = "naraka-macro-viewer"
main = "src/index.js"
compatibility_date = "2024-01-01"

# 静态资源目录
[site]
bucket = "./public"

# D1 数据库绑定
[[d1_databases]]
binding = "DB"
database_name = "naraka-macros"
database_id = "fa14a154-2fb3-4a4d-b7ca-574281c160cb"
